### ISSUE TITLE
Provide option to load API spec from file

### ISSUE THREAD

**Issue by baflo** [XHAlawa/AutoFormsBuilderFilesGenerator#2]
Hey, thank you for starting this project!!

Could you please add an option to load the input file from a local file instead of only `http` or `https`?

**Comment by XHAlawa** [comment]
Hello Baflo 
thanks for this great idea, I'm gonna develop it this week  
but before I start, I'll tell you what I'm goanna do is use a new field called "swaggerFile" to If it exist I'll use it even 
if you provided a URL in "input" field 
if is sutiable for you pleas confirm

**Comment by baflo** [comment]
That sounds great!

**Comment by XHAlawa** [comment]
Pleas Check New Deployed Version 1.0.34
