### ISSUE TITLE
Missing files in package

### ISSUE THREAD

**Issue by matijarmk** [XHAlawa/AutoFormsBuilderFilesGenerator#3]
**Describe the bug**
Published npm package is missing Builders and scriptManager files.  Building application contains this folders.

I think you need to include this files in package.json array

```
  "files": [
    "bin/src/*.js",
    "bin/src/interfaces/*.js",
    "bin/src/templates/*.js",
    "bin/src/Builders/*.js",
    "bin/src/scriptManager/*.js",
  ],
```

I would also recommend installing typescript as dev dependency.

**Screenshots**
![image](https://github.com/XHAlawa/AutoFormsBuilderFilesGenerator/assets/7688695/6ef26436-ef02-4959-b585-11b69c55963c)

**Comment by XHAlawa** [comment]
Hello @matijarmk 
Your Right, I am working on it and there will be a new publish today

**Comment by XHAlawa** [comment]
@matijarmk  Please Check New Version Deployed 1.0.39
