### ISSUE TITLE
Enum properties are undefined/unreferenced in generated FormBuilder -> buildForm()

### ISSUE THREAD

**Issue by MKL-MikaHanke** [XHAlawa/AutoFormsBuilderFilesGenerator#5]
A model with an enum property has errors in its generated FormBuilder. The enum values are undefined/unreferenced when building the form in buildForm(). The following description should clarify what i mean:

**1. Generate models with a api description like this (schemeFile):**
```
"components": {
  "schemas": {
    "Test": {
        "type": "object",
        "properties": {
          "id": {
            "type": "integer"
          },
          "enumRef": {
            "$ref": "#/components/schemas/TestEnum"
          }
        }
      },
      "TestEnum": {
        "enum": [
          "valueA",
          "valueB",
          "valueC"
        ],
        "type": "string"
      }
  }
}
```
**2. Generate the forms:**
Models should look like this:
```
export interface Test { 
    id?: number;
    enumRef?: TestEnum;
}
export namespace Test {
}

export type TestEnum = 'valueA' | 'valueB' | 'valueC';
export const TestEnum = {
    valueA: 'valueA' as TestEnum,
    valueB: 'valueB' as TestEnum,
    valueC: 'valueC' as TestEnum
};
```
The generated TestFormBuilder file should have an error regarding the enum names, because the enum is not imported:
```
@Injectable()
export class TestFormBuilder implements IFormBuilder<Test> {
    // code before ...

    buildForm(model: Test | null = null, 
        additionalControl: { name: string, control?: AbstractControl}[] = []) {
        
        this.form = this.fb.group({
			id:0, 
			enumRef: [ valueA, Validators.compose([ oneOfValidator( [ 
				valueA, valueB, valueC,  ] ) ] )],                  // HERE: errors occur "Cannot find name 'valueA'."
        });

        if (model != null) {
            this.form.patchValue({ ... model });
        }

        additionalControl.forEach(a => {
          this.form.addControl(a.name, a.control ?? new FormControl())
        })

        

        return this.form;
    }

    // code after ...
}
```

![image](https://github.com/XHAlawa/AutoFormsBuilderFilesGenerator/assets/163290548/dc9b3776-236a-453a-96c6-117afa76e223)

---

The best solution would be to import the enum and generate something like this:
```
import { Test, TestEnum } from '../models'; 

// come code ...

this.form = this.fb.group({
    id:0, 
    enumRef: [ TestEnum.valueA, Validators.compose([ oneOfValidator( [ 
        TestEnum.valueA, TestEnum.valueB, TestEnum.valueC,  ] ) ] )],
});
```
But it would also work to turn the expressions into strings:
```
this.form = this.fb.group({
    id:0, 
    enumRef: [ 'valueA', Validators.compose([ oneOfValidator( [ 
        'valueA', 'valueB', 'valueC',  ] ) ] )],
});
```

---

I was using `"angular-formsbuilder-gen": "^1.0.53",`

**Comment by XHAlawa** [comment]
Thanks for you suggestions to improve this package I've covered the 3 scenarios  
1 - Numeric only Enum
2 - Import It As string  
3 - Import From Generated Models 
Both 2 and 3 managed bug flag 'useEnumValuesAsString' 
in swagger.json config file
`
{
    "components": {
        "schemas": {
            "Test": {
                "type": "object",
                "properties": {
                    "id": {
                        "type": "integer"
                    },
                    "enumRef": {
                        "$ref": "#/components/schemas/TestEnum"
                    },
                    "numEnum": {
                        "$ref": "#/components/schemas/TestEnum2"
                    }
                }
            },
            "TestEnum": {
                "enum": [
                    "valueA",
                    "valueB",
                    "valueC"
                ],
                "type": "string"
            },
            "TestEnum2": {
                "type": "integer",
                "description": "",
                "x-enumNames": [
                    "valueA",
                    "valueB",
                    "valueC"
                ],
                "enum": [
                    0,
                    1,
                    2
                ]
            }
        }
    }
}
`

Here is the result 
![image](https://github.com/XHAlawa/AutoFormsBuilderFilesGenerator/assets/46560141/472ce7d6-a883-48e2-b43c-c4dca8bd4866)

Please use next version 1.0.54

**Comment by MKL-MikaHanke** [comment]
Works just fine. 
One small detail: one of our enums uses kabab-case, which is converted to snake_case in the model. We will adjust our api to only use one case, so it should work with the current version of the form builder anyways. But you may want to consider this edge case in your generation process.
Note that the strings are still in kebab-case:

```
export type Test = 'kebab-case' | 'kebab-case-two';

export const Test = {
    kebab_case: 'kebab-case' as Test,
    kebab_case_two: 'kebab-case-two' as Test
};
```

I was using `"angular-formsbuilder-gen": "^1.0.54",`

---

Thanks again for the quick response @XHAlawa

**Comment by XHAlawa** [comment]
@MKL-MikaHanke I'll Start Working on It today, 
I was working on another bug in array patching and providers
-  reported by mail.
